apiVersion: v1
kind: Secret
metadata:
  name: mssql-secrets
type: Opaque
stringData:
  # Replace PLACEHOLDER with the password you chose earlier
  SQLDB_Connection: "Server=mssql.${NAMESPACE}.svc.cluster.local;Database=DurableDB;User ID=sa;Password=${MSSQL_SA_PASSWORD};Persist Security Info=False;TrustServerCertificate=True;Encrypt=True;"
