apiVersion: batch/v1
kind: CronJob
metadata:
  name: xrayconnector-purgehistory
  labels:
    app: xrayconnector
spec:
  schedule: "0 2 * * *" # Every day at 2am
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-container
            image: curlimages/curl:latest
            command:
            - curl
            args:
            - "-X"
            - "POST"
            - "-H"
            - "Content-Type: text/plain" 
            - "-d"
            - "60" # Purge history older than 60 minutes
            # Adjust the function key provided according to your keys defined in xrayconnector.yml 
            - "http://xrayconnector.default.svc.cluster.local/api/PurgeHistory?code=UEktkwvwbjWkjeUsD674WE7yh/Fhr2NL9T1PhbS0cuQ="
          restartPolicy: OnFailure
