
### ### Local testing with kubernetes (e.g. minikube, Docker for Desktop)
#### Test request
GET http://localhost/api/TestPing?code=<YOUR-MASTER-KEY>

#### Start workflow 
POST http://localhost/api/TriggerPeriodicAPIPoller?code=<YOUR-MASTER-KEY>

#### Terminate workflow 
POST http://localhost/api/TerminatePeriodicAPIPoller?code=<YOUR-MASTER-KEY>

### Send test-trace to XRay
POST http://localhost/api/TestGenerateSampleTrace?code=<YOUR-MASTER-KEY>

### Send test-trace to configured backend
POST http://localhost/api/TestSendSampleTrace?code=<YOUR-MASTER-KEY>

### Check status of workflow
POST http://localhost/api/WorkflowWatchdog?code=<YOUR-MASTER-KEY>

### ### Local testing (Azure Function)
#### Test request
GET http://localhost:7217/api/TestPing 

### Start workflow
POST http://localhost:7217/api/TriggerPeriodicAPIPoller 

### Terminate workflow
POST http://localhost:7217/api/TerminatePeriodicAPIPoller 

### Send test-trace to XRay
POST http://localhost:7217/api/TestGenerateSampleTrace

### Send test-trace to configured backend
POST http://localhost:7217/api/TestSendSampleTrace

### Check status of workflow
POST http://localhost:7217/api/WorkflowWatchdog