data:
  # Following function keys to protect your functions, are pre-generated and NEED TO BE REPLACED with new keys to prevent mis-use of the api!
  # When changing the keys, make sure to also adjust the key in the CronJob's ('xrayconnector-watchdog' or 'xrayconnector-purgehistory') url 
  # The keys are encoded in base64
  host.master: VUVrdGt3dndialdramVVc0Q2NzRXRTd5aC9GaHIyTkw5VDFQaGJTMGN1UT0=
  host.function.default: VUVrdGt3dndialdramVVc0Q2NzRXRTd5aC9GaHIyTkw5VDFQaGJTMGN1UT0=
  host.systemKey.default: VUVrdGt3dndialdramVVc0Q2NzRXRTd5aC9GaHIyTkw5VDFQaGJTMGN1UT0=
  functions.terminateinstance.default: VUVrdGt3dndialdramVVc0Q2NzRXRTd5aC9GaHIyTkw5VDFQaGJTMGN1UT0=
  functions.triggerperiodicapipoller.default: VUVrdGt3dndialdramVVc0Q2NzRXRTd5aC9GaHIyTkw5VDFQaGJTMGN1UT0=
  functions.workflowwatchdog.default: VUVrdGt3dndialdramVVc0Q2NzRXRTd5aC9GaHIyTkw5VDFQaGJTMGN1UT0= #MAKE SURE you modify the key at the end of manifest should you CHANGE this!
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-xrayconnector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xrayconnector-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: xrayconnector-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xrayconnector-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: xrayconnector
spec:
  selector:
    app: xrayconnector
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xrayconnector
  labels:
    app: xrayconnector
spec:
  selector:
    matchLabels:
      app: xrayconnector
  template:
    metadata:
      labels:
        app: xrayconnector
    spec:
      containers:
      - name: xrayconnector
        image: nikhilgoenka/xrayconnector:debug
        imagePullPolicy: Always
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: GetRecentTraceIds
        - name: AzureFunctionsJobHost__functions__1
          value: GetTraceDetails
        - name: AzureFunctionsJobHost__functions__2
          value: PeriodicAPIPoller
        - name: AzureFunctionsJobHost__functions__3
          value: ProcessTraces
        - name: AzureFunctionsJobHost__functions__4
          value: RetrieveRecentTraces
        - name: AzureFunctionsJobHost__functions__5
          value: RetrieveTraceDetails
        - name: AzureFunctionsJobHost__functions__6
          value: RetrieveTraceDetails
        - name: AzureFunctionsJobHost__functions__7
          value: TriggerPeriodicAPIPoller
        - name: AzureFunctionsJobHost__functions__8
          value: TerminatePeriodicAPIPoller
        - name: AzureFunctionsJobHost__functions__11
          value: WorkflowWatchdog
        - name: AzureFunctionsJobHost__functions__12
          value: TestPing
        - name: AzureFunctionsJobHost__functions__13
          value: PurgeHistory
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-xrayconnector
        - name: AzureFunctionsJobHost__Logging__LogLevel__DurableTask.SqlServer 
          value: Debug  
        - name: AzureFunctionsJobHost__Logging__LogLevel__DurableTask.Core 
          value: Debug  
        envFrom:
        - secretRef:
            name: connector-config
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: xrayconnector-function-keys-identity-svc-act
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: xrayconnector
  labels: {}
spec:
  scaleTargetRef:
    name: xrayconnector
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: mssql
    metadata:
      query: SELECT dt.GetScaleRecommendation(8, 8)
      targetValue: "1"
      connectionStringFromEnv: SQLDB_Connection
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: xray-watchdog
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-container
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - |
              curl -X POST "http://xrayconnector/api/WorkflowWatchdog?code=UEktkwvwbjWkjeUsD674WE7yh/Fhr2NL9T1PhbS0cuQ="
          restartPolicy: OnFailure

