replicaCount: 1

image:
  repository: nikhilgoenka/xrayconnector
  tag: debug
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

autoscaling:
  minReplicaCount: 1
  maxReplicaCount: 5
  query: "SELECT dt.GetScaleRecommendation(8, 8)"
  targetValue: "1"

cronjob:
  schedule: "*/3 * * * *"

# Function keys (base64-encoded). These must be replaced.
secrets:
  hostMaster: "VUVrdGt3dndialdramVVc0Q2NzRXRTd5aC9GaHIyTkw5VDFQaGJTMGN1UT0="
  hostFunctionDefault: "VUVrdGt3dndialdramVVc0Q2NzRXRTd5aC9GaHIyTkw5VDFQaGJTMGN1UT0="
  hostSystemKeyDefault: "VUVrdGt3dndialdramVVc0Q2NzRXRTd5aC9GaHIyTkw5VDFQaGJTMGN1UT0="
  terminateInstance: "VUVrdGt3dndialdramVVc0Q2NzRXRTd5aC9GaHIyTkw5VDFQaGJTMGN1UT0="
  triggerPoller: "VUVrdGt3dndialdramVVc0Q2NzRXRTd5aC9GaHIyTkw5VDFQaGJTMGN1UT0="
  workflowWatchdog: "VUVrdGt3dndialdramVVc0Q2NzRXRTd5aC9GaHIyTkw5VDFQaGJTMGN1UT0="
  purgeHistory: "VUVrdGt3dndialdramVVc0Q2NzRXRTd5aC9GaHIyTkw5VDFQaGJTMGN1UT0="

# Connector config secret (what your Deployment loads via envFrom: connector-config)
connector:
  sqlConnection: "Server=mssql;Database=DurableDB;User Id=sa;Password=ReplaceMe!;" 
  otlpEndpoint: ""                          # e.g. https://<tenant>.live.dynatrace.com/api/v2/otlp/v1/traces
  otlpAuth: ""                              # e.g. Api-Token dt0c01...
  awsRoleArn: ""
  awsRegion: "us-east-1"
  awsIdentityKey: ""
  awsSecretKey: ""
  pollingInterval: "60"
  autoStart: "true"

# Optional: automatically create DurableDB after install/upgrade
dbSetup:
  enabled: false
  host: "mssql"       # service DNS of your SQL Server
  user: "sa"
  password: ""        # set if enabled
  name: "DurableDB"
