apiVersion: batch/v1
kind: CronJob
metadata:
  name: xray-watchdog
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: curl-container
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - |
              curl -X POST "http://xrayconnector/api/WorkflowWatchdog?code={{ .Values.secrets.workflowWatchdog }}"
