{{- if .Values.dbSetup.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-db-setup"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: sqlcmd
        image: mcr.microsoft.com/mssql-tools
        command:
        - /bin/sh
        - -c
        - |
          /opt/mssql-tools/bin/sqlcmd -S {{ .Values.dbSetup.host }} -U {{ .Values.dbSetup.user }} -P "{{ .Values.dbSetup.password }}" -Q "IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = '{{ .Values.dbSetup.name }}') CREATE DATABASE [{{ .Values.dbSetup.name }}] COLLATE Latin1_General_100_BIN2_UTF8"
  backoffLimit: 2
{{- end }}
