apiVersion: apps/v1
kind: Deployment
metadata:
  name: xrayconnector
  labels:
    app: xrayconnector
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: xrayconnector
  template:
    metadata:
      labels:
        app: xrayconnector
    spec:
      serviceAccountName: xrayconnector-function-keys-identity-svc-act
      containers:
      - name: xrayconnector
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: GetRecentTraceIds
        - name: AzureFunctionsJobHost__functions__1
          value: GetTraceDetails
        - name: AzureFunctionsJobHost__functions__2
          value: PeriodicAPIPoller
        - name: AzureFunctionsJobHost__functions__3
          value: ProcessTraces
        - name: AzureFunctionsJobHost__functions__4
          value: RetrieveRecentTraces
        - name: AzureFunctionsJobHost__functions__5
          value: RetrieveTraceDetails
        - name: AzureFunctionsJobHost__functions__6
          value: RetrieveTraceDetails
        - name: AzureFunctionsJobHost__functions__7
          value: TriggerPeriodicAPIPoller
        - name: AzureFunctionsJobHost__functions__8
          value: TerminatePeriodicAPIPoller
        - name: AzureFunctionsJobHost__functions__11
          value: WorkflowWatchdog
        - name: AzureFunctionsJobHost__functions__12
          value: TestPing
        - name: AzureFunctionsJobHost__functions__13
          value: PurgeHistory
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-xrayconnector
        - name: AzureFunctionsJobHost__Logging__LogLevel__DurableTask.SqlServer
          value: Debug
        - name: AzureFunctionsJobHost__Logging__LogLevel__DurableTask.Core
          value: Debug
        envFrom:
        - secretRef:
            name: connector-config
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
        startupProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
