apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-xrayconnector
type: Opaque
stringData:
  host.master: {{ .Values.secrets.hostMaster | quote }}
  host.function.default: {{ .Values.secrets.hostFunctionDefault | quote }}
  host.systemKey.default: {{ .Values.secrets.hostSystemKeyDefault | quote }}
  functions.terminateinstance.default: {{ .Values.secrets.terminateInstance | quote }}
  functions.triggerperiodicapipoller.default: {{ .Values.secrets.triggerPoller | quote }}
  functions.workflowwatchdog.default: {{ .Values.secrets.workflowWatchdog | quote }}
