apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
rules:
- apiGroups: [""]
  resources: ["secrets", "configMaps"]
  verbs: ["get","list","watch","create","update","patch","delete"]
