apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xrayconnector-function-keys-identity-svc-act-functions-keys-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: xrayconnector-function-keys-identity-svc-act
