apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: xrayconnector
spec:
  scaleTargetRef:
    name: xrayconnector
  minReplicaCount: {{ .Values.autoscaling.minReplicaCount }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicaCount }}
  triggers:
  - type: mssql
    metadata:
      query: {{ .Values.autoscaling.query | quote }}
      targetValue: "{{ .Values.autoscaling.targetValue }}"
      connectionStringFromEnv: SQLDB_Connection
