apiVersion: v1
kind: Service
metadata:
  name: xrayconnector
spec:
  selector:
    app: xrayconnector
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80
  type: {{ .Values.service.type }}
