# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["XRayConnector/XRayConnector.csproj", "XRayConnector/"]
RUN dotnet restore "./XRayConnector/XRayConnector.csproj"
COPY . .
WORKDIR "/src/XRayConnector"
RUN dotnet build "./XRayConnector.csproj" -c $BUILD_CONFIGURATION -o /app/build 

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./XRayConnector.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false 

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM mcr.microsoft.com/azure-functions/dotnet:4 AS base
WORKDIR /home/site/wwwroot
COPY --from=publish /app/publish .
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

